apiVersion: v1
kind: Service
metadata:
  name: codemonkeybank-service
spec:
 selector:
   app: codemonkeybank-webapp
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
type: {{ .Values.serviceType }}