apiVersion: apps/v1
kind: Deployment
metadata:
 name: codemonkeybank-webapp 
spec:
 replicas: 1
 selector:
   matchLabels:
     app: codemonkeybank-webapp
 template:
   metadata:
     labels:
       app: codemonkeybank-webapp
   spec:
     containers:
     - name: codemonkeybank-container
       image: ghcr.io/tinsve/codemonkeybank:5acb4cc4b591d7a863fdf04c97857293d8ecc962
       ports:
       - containerPort: 80
       envFrom: 
       - configMapRef:
           name: app-config    
