apiVersion: apps/v1
kind: Deployment
metadata:
 name: codemonkeybank-webapp
 namespace: cmb
spec:
 replicas: 1
 selector:
   matchLabels:
     app: codemonkeybank-webapp
 template:
   metadata:
     labels:
       app: codemonkeybank-webapp
   spec:
     containers:
     - name: codemonkeybank-container
       image: ghcr.io/tinsve/codemonkeybank:5c8fa38c3289a4b1e3d4ff8898b8ebc1551ea7df
       ports:
       - containerPort: 80
       envFrom: 
       - configMapRef:
           name: app-config    
