name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
    - 'CodeMonkeyBank/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Login to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    # Build and push the Docker image
    - name: Build and Push Docker image
      run: |
        cd CodeMonkeyBank
        docker build -t ghcr.io/tinsve/codemonkeybank:${{ github.sha }} .
        docker push ghcr.io/tinsve/codemonkeybank:${{ github.sha }}

    # Update the Kubernetes manifests to use the new image tag
    - name: Update Kubernetes manifests
      run: |
        sed -i 's|ghcr.io/tinsve/codemonkeybank:.*|ghcr.io/tinsve/codemonkeybank:${{ github.sha }}|' CodeMonkeyBank-K8S-Manifests/codemonkeybank-deployment.yaml

    # Commit and push the updated manifests back to the repository
    - name: Commit and push updated manifests
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add CodeMonkeyBank-K8S-Manifests/codemonkeybank-deployment.yaml
        git commit -m "Update webapp image to ${{ github.sha }}"
        git push